import { Button, CircularProgress, Stack } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useCallback } from "react";

import { useStateContext } from "@/context";

export default function Home() {
  const router = useRouter();

  const {
    wallet: { accounts },
    isLoading,
    connectMetaMask,
  } = useStateContext();

  const onRedirectToMetamask = useCallback(() => {
    router.push("/metamask");
  }, []);

  const onRedirectToCosmos = useCallback(() => {
    router.push("/cosmos");
  }, []);

  const onConnectToMetamaskHandler = useCallback(() => {
    accounts.length
      ? onRedirectToMetamask()
      : connectMetaMask(onRedirectToMetamask);
  }, [accounts.length, connectMetaMask, router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Stack
            width={"100vw"}
            height={"100vh"}
            justifyContent={"center"}
            alignItems={"center"}
          >
            <Stack flexDirection={"row"} gap={"32px"}>
              <Button
                onClick={onConnectToMetamaskHandler}
                variant={"contained"}
                disabled={isLoading}
              >
                {isLoading ? (
                  <CircularProgress color={"info"} />
                ) : accounts.length ? (
                  "To metamask"
                ) : (
                  "Connect to metamask"
                )}
              </Button>

              <Button
                onClick={onRedirectToCosmos}
                variant={"contained"}
                disabled={isLoading}
              >
                To cosmos
              </Button>
            </Stack>
          </Stack>
        </div>
      </main>
    </>
  );
}
