import Head from "next/head";
import { Box, Button, CircularProgress } from "@mui/material";
import { useRouter } from "next/router";
import { useStateContext } from "@/context";
import React, { useCallback, useEffect } from "react";

export default function Home() {
  const router = useRouter();

  const {
    wallet: { accounts },
    isLoading,
    connectMetaMask,
  } = useStateContext();

  const onRedirect = () => {
    router.push("/metamask");
  };

  const onConnectToMetamaskHandler = useCallback(() => {
    accounts.length ? onRedirect() : connectMetaMask(onRedirect);
  }, [accounts.length, connectMetaMask, router]);

  useEffect(() => {
    accounts.length && router.push("/metamask");
  }, [accounts]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Box>
            <Button
              onClick={onConnectToMetamaskHandler}
              variant={"contained"}
              disabled={isLoading}
            >
              {isLoading ? <CircularProgress color={"info"} /> : "Connect"}
            </Button>
          </Box>
        </div>
      </main>
    </>
  );
}
